# thanks to https://github.com/travis-ci/travis-ci/issues/5775
env:
  - NOT_CRAN=true

sudo: false

addons:
  apt:
    packages:
      - libxml2-dev libgit2-dev

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

before_install:
  - cd pkg

after_success:
  - Rscript -e 'covr::coveralls()'
